apiVersion: apps/v1
kind: Deployment
metadata:
    name: cartservice
    labels:
        app: cartservice
    spec:
        replicas: 1
        selector:
            matchLabels:
                app: cartservice
        template:
            metadata:
                labels:
                    app: cartservice
            spec:
                containers:
                    - name : cartservice
                      image: ghcr.io/<tvuj-username>/cartservice:latest  # TODO: nahraï adresou tvého image v ACR/GHCR
                      ports:
                        - containerPort: 8080
                      env:
                        - name: ASPNETCORE_ENVIRONMENT
                          value: "Production"
                        - name: ConnectionStrings__DefaultConnection
                          value: "Server=sqldb;Database=ECommerceApp_CartDb;User Id=sa;Password=ECom2025!Pass;TrustServerCertificate=True;"
                        - name: OrderService__GrpcAddress
                          value: "http://orderservice:8080"
                        - name: ProductService__GrpcAddress
                          value: "http://productservice:8080"
                        - name: EnableSwagger
                          value: "true"

                        - name: Jwt__Key
                          valueFrom:
                            secretKeyRef:
                              name: ecommerce-secrets
                              key: Jwt__Key
                        - name: Jwt__Issuer
                          valueFrom:
                            secretKeyRef:
                              name: ecommerce-secrets
                              key: Jwt__Issuer
                        - name: Jwt__Audience
                          valueFrom:
                            secretKeyRef:
                              name: ecommerce-secrets
                              key: Jwt__Audience
                        - name: RabbitMq__Username
                          valueFrom:
                            secretKeyRef:
                              name: ecommerce-secrets
                              key: RabbitMq__Username
                        - name: RabbitMq__Password
                          valueFrom:
                            secretKeyRef:
                              name: ecommerce-secrets
                              key: RabbitMq__Password
                        - name: RabbitMq__Host
                          value: "rabbitmq"
                        - name: RabbitMq__VirtualHost
                          value: "/"



---
apiVersion: v1
kind: Service
metadata:
    name: cartservice
    labels:
        app: cartservice
spec:
    selector:
        app: cartservice
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: ClusterIP