apiVersion: v1
kind: Secret
metadata:
    name: ecommerce-secrets
type: Opaque
stringData:
    # JWT
    Jwt__Key: "a851091109b0dad8b3834341577e990f"
    Jwt__Issuer: "ECommerceApp.AuthService"
    Jwt__Audience: "ECommerceApp.Frontend"

    # RabbitMQ
    RabbitMq__Username: "guest"
    RabbitMq__Password: "guest"

    # Stripe (používá PaymentService)
    Stripe__SecretKey: "sk_test_51S3KcYFzAPsvRxZYNAeAVNsDoNVIPh7ZGa0FuHzvF8NC52FxfNlmbzhsYQw5FYZb81WqG5ZMq5wzyIUZji7nnrxj00qaSyPz5D"
    Stripe__WebHookSecret: "whsec_915baf41d3cb0adcaebd3029758b2d0b7b06ecb5a6891086ffc74ffd94c5c3cf"