apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice
  namespace: ecommerceapp
  labels:
    app: deliveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryservice
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice
          image: ghcr.io/jakubkopecky-dev/deliveryservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__DefaultConnection

            - name: MessageBroker__Transport
              value: "AzureServiceBus"
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: AzureServiceBus__ConnectionString

            - name: OrderService__GrpcAddress
              value: "http://orderservice:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
  namespace: ecommerceapp
  labels:
    app: deliveryservice
spec:
  selector:
    app: deliveryservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
