apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice
  labels:
    app: deliveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryservice
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice
          image: ghcr.io/<your-username>/deliveryservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # ASP.NET Core runtime environment
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            # Message broker switch (RabbitMQ / AzureServiceBus)
            - name: MessageBroker__Transport
              value: "RabbitMq"

            # Database connection string (DeliveryDb)
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__DeliveryDb

            # gRPC address of dependent services
            - name: OrderService__GrpcAddress
              value: "http://orderservice:8080"

            # Enable Swagger UI
            - name: EnableSwagger
              value: "true"

            # JWT secrets
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            # RabbitMQ credentials
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: RabbitMq__Username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: RabbitMq__Password
            - name: RabbitMq__Host
              value: "rabbitmq"
            - name: RabbitMq__VirtualHost
              value: "/"

---
apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
  labels:
    app: deliveryservice
spec:
  selector:
    app: deliveryservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
