apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  namespace: ecommerceapp
  labels:
    app: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: ghcr.io/jakubkopecky-dev/gatewayservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
  namespace: ecommerce
  labels:
    app: gatewayservice
spec:
  selector:
    app: gatewayservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
