apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  namespace: ecommerceapp
  labels:
    app: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: ghcr.io/jakubkopecky-dev/notificationservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__DefaultConnection

            - name: MessageBroker__Transport
              value: "AzureServiceBus"
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: AzureServiceBus__ConnectionString
            - name: AzureServiceBus__QueueName
              value: "notification-queue"
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  namespace: ecommerce
  labels:
    app: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
