apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: ecommerceapp
  labels:
    app: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: productservice
          image: ghcr.io/jakubkopecky-dev/productservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__DefaultConnection

            - name: MessageBroker__Transport
              value: "AzureServiceBus"
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: AzureServiceBus__ConnectionString
            - name: AzureServiceBus__QueueName
              value: "product-queue"
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: ecommerceapp
  labels:
    app: productservice
spec:
  selector:
    app: productservice
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
