apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: ghcr.io/<your-username>/userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            # Database connection (UserDb)
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__UserDb

            # JWT
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience
            - name: Jwt_ExpiresInMinutes
              value: "600"

            - name: EnableSwagger
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
