name: CI/CD Pipeline
          
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    # 1) Build and test all services
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build solution
              run: dotnet build --no-restore --configuration Release

            - name: Run tests
              run: dotnet test --no-build --configuration Release --verbosity normal

    # 2) Build & push docker images (multi-arch)
    docker-build:
        runs-on: ubuntu-latest
        needs: build-and-test
        strategy:
            matrix:
                service: 
                    - CartService
                    - OrderService
                    - ProductService
                    - DeliveryService
                    - NotificationService
                    - PaymentService
                    - UserService
                    - GatewayService

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: jakubkopecky-dev
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push ${{ matrix.service }}
              run: |
                  SERVICE_TAG=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
                  COMMIT_TAG=${{ github.sha }}

                  if [ "${{ matrix.service }}" = "GatewayService" ]; then
                      DOCKERFILE="GatewayService/Dockerfile"
                  else
                      DOCKERFILE="${{ matrix.service }}.Api/Dockerfile"
                  fi

                  IMAGE_NAME=ghcr.io/jakubkopecky-dev/$SERVICE_TAG

                  echo "Building $IMAGE_NAME:$COMMIT_TAG for linux/amd64"

                  docker buildx build \
                      --platform linux/amd64 \
                      -t $IMAGE_NAME:$COMMIT_TAG \
                      -f $DOCKERFILE \
                      --push .

    # 3) Deploy to Azure Kubernetes Service (AKS)
    deploy-to-aks:
        runs-on: ubuntu-latest
        needs: docker-build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Get AKS credentials
              run: |
                  az aks get-credentials \
                      --resource-group ecommerceapp-rg \
                      --name ecommerceapp-aks \
                      --overwrite-existing

            - name: Create namespace (if not exists)
              run: |
                  kubectl create namespace ecommerceapp --dry-run=client -o yaml | kubectl apply -f -

            - name: Create GHCR image pull secret
              run: |
                  kubectl create secret docker-registry ghcr-secret \
                      --docker-server=ghcr.io \
                      --docker-username=jakubkopecky-dev \
                      --docker-password=${{ secrets.GHCR_TOKEN }} \
                      --namespace=ecommerceapp --dry-run=client -o yaml | kubectl apply -f -

            - name: Apply Kubernetes manifests
              run: |
                  echo "Applying Kubernetes manifests..."
                  kubectl apply -f k8s/namespace.yaml
                  kubectl apply -f k8s/

            - name: Set container images to current commit
              run: |
                  COMMIT_TAG=${{ github.sha }}
                  for svc in cartservice orderservice productservice deliveryservice notificationservice paymentservice userservice gatewayservice; do
                      echo "Updating image for $svc..."
                      kubectl set image deployment/$svc "*=ghcr.io/jakubkopecky-dev/${svc}:${COMMIT_TAG}" -n ecommerceapp
                  done

            - name: Wait for deployments to roll out
              run: |
                  for svc in cartservice orderservice productservice deliveryservice notificationservice paymentservice userservice gatewayservice; do
                      echo "Checking rollout status for $svc..."
                      kubectl rollout status deployment/$svc -n ecommerceapp --timeout=180s || {
                          echo "Deployment of $svc failed."
                          kubectl describe deploy/$svc -n ecommerceapp || true
                          kubectl describe pods -l app=$svc -n ecommerceapp || true
                          kubectl logs -l app=$svc -n ecommerceapp --tail=80 || true
                          exit 1
                      }
                  done

            - name: Verify deployment status
              run: |
                  echo "Current pods:"
                  kubectl get pods -n ecommerceapp -o wide
                  echo "Services:"
                  kubectl get svc -n ecommerceapp
