name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1) Build and test all services
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  # 2) Build & push docker images (matrix for each microservice)
  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    strategy:
      matrix:
        service: 
          - CartService
          - OrderService
          - ProductService
          - DeliveryService
          - NotificationService
          - PaymentService
          - UserService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jakubkopecky-dev
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        run: |
          SERVICE_TAG=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/jakubkopecky-dev/$SERVICE_TAG:latest -f ${{ matrix.service }}.Api/Dockerfile .
          docker push ghcr.io/jakubkopecky-dev/$SERVICE_TAG:latest

  # 3) Deploy to Azure Container Apps
  deploy-to-aca:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy CartService
        run: |
          az containerapp update \
            --name cartservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/cartservice:latest

      - name: Deploy OrderService
        run: |
          az containerapp update \
            --name orderservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/orderservice:latest

      - name: Deploy ProductService
        run: |
          az containerapp update \
            --name productservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/productservice:latest

      - name: Deploy DeliveryService
        run: |
          az containerapp update \
            --name deliveryservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/deliveryservice:latest

      - name: Deploy NotificationService
        run: |
          az containerapp update \
            --name notificationservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/notificationservice:latest

      - name: Deploy PaymentService
        run: |
          az containerapp update \
            --name paymentservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/paymentservice:latest

      - name: Deploy UserService
        run: |
          az containerapp update \
            --name userservice \
            --resource-group ecommerceapp-rg \
            --image ghcr.io/jakubkopecky-dev/userservice:latest
