name: CI/CD Pipeline

on:
    push:
        branches:
            - main          
    pull_request:
        branches:
            - main          
    workflow_dispatch:      


jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        # 1) Checkout repository
        - name: Checkout code
          uses: actions/checkout@v4

        # 2) Setup .NET SDK
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'     # verze netu projektu

        # 3) Restore & Build
        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore --configuration Release

        # 4) Run tests
        - name: Run tests
          run: dotnet test --no-build --configuration Release --verbosity normal

        # 5) Log in to GitHub Container Registry
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GHCR-Push }}

        # 6) Build & Push Docker image for all microservices
        - name: Build and push CartService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/cartservice:latest -f CartService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/cartservice:latest

        - name: Build and push OrderService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/orderservice:latest -f OrderService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/orderservice:latest

        - name: Build and push ProductService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/productservice:latest -f ProductService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/productservice:latest
    
        - name: Build and push DeliveryService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/deliveryservice:latest -f DeliveryService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/deliveryservice:latest
    
        - name: Build and push NotificationService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/notificationservice:latest -f NotificationService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/notificationservice:latest
    
        - name: Build and push PaymentService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/paymentservice:latest -f PaymentService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/paymentservice:latest
    
        - name: Build and push UserService
          run: |
              docker build -t ghcr.io/jakubkopecky-dev/userservice:latest -f UserService.Api/Dockerfile .
              docker push ghcr.io/jakubkopecky-dev/userservice:latest
