name: CI/CD Pipeline

on:
    push:
        branches:
            - main          
    pull_request:
        branches:
            - main          
    workflow_dispatch:      


jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        # 1) Checkout repository
        - name: Checkout code
          uses: actions/checkout@v4

        # 2) Setup .NET SDK
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'     # verze netu projektu

        # 3) Restore & Build
        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore --configuration Release

        # 4) Run tests
        - name: Run tests
          run: dotnet test --no-build --configuration Release --verbosity normal

        # 5) Log in to GitHub Container Registry
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

        # 6) Build & Push Docker image for all microservices
        - name: Build and push CartService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/cartservice:latest ./CartService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/cartservice:latest

        - name: Build and push OrderService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/orderservice:latest ./OrderService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/orderservice:latest

        - name: Build and push ProductService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner }}/productservice:latest ./ProductService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/productservice:latest
    
        - name: Build and push DeliveryService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/deliveryservice:latest ./DeliveryService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/deliveryservice:latest
    
        - name: Build and push NotificationService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/notificationservice:latest ./NotificationService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/notificationservice:latest
    
        - name: Build and push PaymentService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/paymentservice:latest ./PaymentService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/paymentservice:latest
    
        - name: Build and push UserService
          run: |
              docker build -t ghcr.io/${{ github.repository_owner | toLower }}/userservice:latest ./UserService.Api
              docker push ghcr.io/${{ github.repository_owner | toLower }}/userservice:latest
