name: CI/CD Pipeline
          
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    # 1) Build and test all services
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build solution
              run: dotnet build --no-restore --configuration Release

            - name: Run tests
              run: dotnet test --no-build --configuration Release --verbosity normal

    # 2) Build & push docker images (matrix for each microservice)
    docker-build:
        runs-on: ubuntu-latest
        needs: build-and-test
        strategy:
            matrix:
                service: 
                    - CartService
                    - OrderService
                    - ProductService
                    - DeliveryService
                    - NotificationService
                    - PaymentService
                    - UserService
                    - GatewayService

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: jakubkopecky-dev
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push ${{ matrix.service }}
              run: |
                  SERVICE_TAG=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
                  COMMIT_TAG=${{ github.sha }}

                  if [ "${{ matrix.service }}" = "GatewayService" ]; then
                      DOCKERFILE="GatewayService/Dockerfile"
                  else
                      DOCKERFILE="${{ matrix.service }}.Api/Dockerfile"
                  fi

                  IMAGE_NAME=ghcr.io/jakubkopecky-dev/$SERVICE_TAG

                  echo "Building $IMAGE_NAME:$COMMIT_TAG"

                  docker build -t $IMAGE_NAME:$COMMIT_TAG -f $DOCKERFILE .
                  docker push $IMAGE_NAME:$COMMIT_TAG

    # 3) Deploy to Azure Kubernetes Service (AKS)
    deploy-to-aks:
        runs-on: ubuntu-latest
        needs: docker-build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Get AKS credentials
              run: |
                  az aks get-credentials \
                      --resource-group ecommerceapp-rg \
                      --name ecommerceapp-aks \
                      --overwrite-existing

            - name: Set image tags in Kubernetes manifests
              run: |
                  COMMIT_TAG=${{ github.sha }}
                  for svc in cartservice orderservice productservice deliveryservice notificationservice paymentservice userservice gatewayservice; do
                      echo "Updating image tag for $svc..."
                      yq e -i ".spec.template.spec.containers[0].image = \"ghcr.io/jakubkopecky-dev/${svc}:${COMMIT_TAG}\"" k8s/${svc}.yaml
                  done

            - name: Apply Kubernetes manifests
              run: |
                  echo "Applying Kubernetes manifests..."
                  kubectl apply -f k8s/

            - name: Wait for all deployments to roll out
              run: |
                  echo "Waiting for all deployments to successfully roll out..."
                  for svc in cartservice orderservice productservice deliveryservice notificationservice paymentservice userservice gatewayservice; do
                      echo "Checking rollout status for $svc..."
                      kubectl rollout status deployment/$svc -n ecommerceapp --timeout=180s || {
                          echo "Deployment of $svc failed."
                          kubectl describe pods -l app=$svc -n ecommerceapp
                          kubectl logs -l app=$svc -n ecommerceapp --tail=50
                          exit 1
                      }
                  done

            - name: Verify deployment status
              run: |
                  echo "Final pod status:"
                  kubectl get pods -n ecommerceapp -o wide
